### ISSUE TITLE
转码为epub或其他阅读格式

### ISSUE THREAD

**Issue by tomuGo** [taizihuang/wmyblog#10]
你好，谷歌云盘里的pdf使用了两列排版的样式，如下图：
![image](https://github.com/taizihuang/wmyblog/assets/24789356/1ec60553-8af9-42e2-a83b-09f1553d8edc)
该排版样式，转码为mobi或者epub等格式时，会造成段落混乱。
如果您有完整单列的pdf或者其他完整的原始文档，可以发我一下么

**Comment by taizihuang** [comment]
我重新整理了 Google Drive 中的文件，增加了单列版的pdf。不过 epub 最好还是用html版生成，pdf转码总是有格式上的瑕疵。

你可以访问 book.wmyblog.site 下载最新的 release。后续关于《文集》格式的讨论，请在我的另一个repo 【wmybook】中开 isssue。
