### ISSUE TITLE
"王孟源 x 龙行天下" RSS 近几个月条目的 pubDate 不正确

### ISSUE THREAD

**Issue by daujyungx** [taizihuang/wmyblog#11]
https://taizihuang.github.io/wmyblog/podcast/podcast-long.xml 2024 年 5 月以后条目的 `pubDate` 没有年份, 影响 RSS 阅读器和播客播放器的使用.

**Comment by taizihuang** [comment]
好的，我待会儿更新一下。不过音频链接只有王先生上节目的那一周有效（主要是我懒得每周更新一下cookie...）。

**Comment by daujyungx** [comment]
还有, RSS 条目的排序, 能否改成从新到旧排序?

**Comment by taizihuang** [comment]
你用的什么阅读器？我用 Inoreader 显示正常 https://www.inoreader.com/feed/https%3A%2F%2Ftaizihuang.github.io%2Fwmyblog%2Frss.xml

**Comment by taizihuang** [comment]
@daujyungx 我在Follow平台看到你了:-)
