### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by Miss1990s** [taizihuang/wmyblog#2]
无处留言，只能在此感谢。

我一直想备份王博blog, 但因才疏学浅，一直搁置。

直到遇见了你，对你真的佩服加感谢。

我曾是一个程序员，但不做web；
我喜欢交流，可惜用王博的世界观 在普适社会几乎无人能谈；若你愿意，可加v慢聊 15327522321

**Comment by taizihuang** [comment]
不客气。要点就这些：找到文章评论和最新评论的XHR链接，用bs4筛选出需要的网页元素；将获取的所有数据与wmyblog.github.io内的json数据合并，保存成DataFrame格式，方便索引查找；设置Github Pages 和Actions自动化。所有代码都放上去了，有兴趣可以自己看一下。

如果有编程技术类的问题，欢迎邮件讨论，地址在个人信息下。我个人很现实，不会在网上讨论时政问题，因为见识浅又无法改变什么，认定这是件无意义的事情。

**Comment by Miss1990s** [comment]
哈哈哈，我不是要跟人讨论时政。只是想多认识一些同价值观的朋友，哈哈哈哈。&nbsp;

何 思念 
 15271935241
 

&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: "Taizi ***@***.***&gt;; 
Date: 2021年4月19日(星期一) 上午9:58
To: ***@***.***&gt;; 
Cc: "He ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [taizihuang/wmyblog] 感谢 (#2)





 
不客气。要点就这些：找到文章评论和最新评论的XHR链接，用bs4筛选出需要的网页元素；将获取的所有数据与wmyblog.github.io内的json数据合并，保存成DataFrame格式，方便索引查找；；设置Github Pages 和Actions自动化。所有代码都放上去了，有兴趣可以自己看一下。
 
如果有编程技术类的问题，欢迎邮件讨论，地址在个人信息下。我个人很现实，不会在网上讨论时政问题，因为见识浅又无法改变什么，认定这是件无意义的事情。

**Comment by Miss1990s** [comment]
对了，还有一个问题。请问你知道如何把 王博的繁体离线html编程简体字吗？

**Comment by taizihuang** [comment]
可参考：https://github.com/BYVoid/OpenCC
