### ISSUE TITLE
原博客评论排序问题

### ISSUE THREAD

**Issue by ttian28** [taizihuang/wmyblog#3]
您好，感谢您制作整理王老师的博客。
发现一个问题，王老师会在评论区删除不必要的评论，那么udn平台会给评论重新排序，比如删除66楼，那么原67楼就会自动变成66楼。程序采集的时候没有注意到这个问题，会保留原66楼的评论，新66楼就没有了，不知能否改善。

**Comment by taizihuang** [comment]
请问这个例子是哪篇博文的？我看看

**Comment by ttian28** [comment]
> 请问这个例子是哪篇博文的？我看看

比如最新的这一篇《【國際】【宣傳】如何破解當前歐美的宣傳攻勢》，目前您采集了86条评论，但是排在前面的4条由ID“大一統理論”所留的留言，早已经被删除了（实际上他的留言经常被王先生删除），后面填补上来的留言没有采集到。应该就是重新排序的问题。

**Comment by taizihuang** [comment]
你好，我邮件收到了你的回复，你是后来删掉了吗？我检查了一下《【國際】【宣傳】如何破解當前歐美的宣傳攻勢》采集到的评论，只多不少，不存在填补上来的评论没有采集到的问题。请指明哪条评论没有被采集到，谢谢！
