### ISSUE TITLE
with open('./html/'+art_id+'.html','w') as f ——>with open("index.html", "w") as index:

### ISSUE THREAD

**Issue by Miss1990s** [taizihuang/wmyblog#4]
with open('./html/'+art_id+'.html','w') as f ——>with open("index.html", "w") as index:
我想用文件搜索软件对每篇文章进行 检索/分析，使用过程发现 html文件名为art_id 不太友好，可否将每篇文件的html文件名 改成 索引用的名字 ；
如果不难的话，如能批量导出html为PDF最佳

p.s. 我最近加了王孟源粉丝群（七公读者群，目前101人），不知道兄台是否已经加入。

**Comment by taizihuang** [comment]
你好，如果想要检索分析，我想用不上分析单个html文件。文章和评论的数据都在 ./data/article_full.pkl 和 ./data/comment_full.pkl 内，用python>3.9.5 就能读入。用art_id是为了和王博士udn上的博文id对应，因为标题是有可能小改动的，比如最近就将“中共”改成了“中国”会引起一些不必要的麻烦。

用pandoc就能转码。因为正文、评论和回复每天都在变动，转成PDF一个是臃肿，再一个是不容易体现这些更新，所以没找到比较好的方案。你是希望打印出来吗？

我没有入群，暂时也不太想进，谢谢。

**Comment by Miss1990s** [comment]
明白了用id作为文件名的意义（原来还会改名字），那么我不知可否 一键批量导出PDF，
用途：
1. 本地搜索 快 而且 更加准确——【测试】 我稍微用一个关键词搜索了一下：贵站搜索只列出9篇文章，而真实的远不止这一些（至少33个）。
2. 以后也会打印成本，更适合分享一些学生看。
3. 我本人用Chrome插件已经批量下载了所有PDF，不仅费时费力，而且还会遗漏（留言只有第一页；Chrome自带打印竟然会漏行）；尽管如此，群友多人问我要PDF文件（他们知道这个备份地址，但似乎还是对PDF更加青睐）。


兄台都是一番心血在无私奉献，万分感谢！
虽有期待，但此事并不紧急，如果可行的话，有闲的时候再弄即可。
祝安！

**Comment by taizihuang** [comment]
你太客气了，能否告知关键词是什么？我测试一下。不太相信搜索会遗漏。

手动下载确实很累，这个流程可以完全自动化。请问你要求的PDF格式是否是包含所有评论和回复？按照发表时间逆序排列？

我这个镜像包含了王博士删掉的提问，所以稍显杂乱。之所以不删是因为我觉得对数据尽量不做减法比较好。

**Comment by Miss1990s** [comment]
我大概知道搜索结果区别的原因了：我是用 用户名（例如【越雷】）进行检索的，而你的搜索范围并没有包含用户名。

PDF文件需要包含 正文+评论和回复 (目前的html内容即可）。
文件名命名规则 ：发表日期 + 空格 + 发表时间hour + 文章名.pdf。 eg. "2014-09-18 21【美国】【戦略】 从乌克兰看今日美俄的政略与戦略 .pdf"；默认排序为发表时间逆序；
如此命名是为了 1.下载后能按照发表时间进行文件排序；2. 能够按照文章类别（eg.【戦略】）找到此类别的所有文章；

THX!

**Comment by taizihuang** [comment]
现在已经可以用网友名搜索了。

PDF已经转好放在pdf文件夹中。

**Comment by Miss1990s** [comment]
Bro, 试读了几篇PDF，给你满分！

**Comment by Miss1990s** [comment]
目前在用大模型的帮助下复习王博的blog，在把文章输入到NoteBookLM作为知识库会遇到一些问题：1.不能从udn blog的文章链接读取内容（打不开链接）；2. 镜像https://wmyblog.site/下的文章链接会丢失留言内容；3. PDF文件作为知识库现在会把作者回复当做读者留言，所以需要在留言栏中添加作者标签。

![Image](https://github.com/user-attachments/assets/f579c520-59ee-49eb-94e0-d82ce227d576)

**Comment by taizihuang** [comment]
文章和评论的数据都在 ./data/article_full.pkl 和 ./data/comment_full.pkl，你可以写一个 Python 程序，生成想要的文本格式。如果有困难，可以问问 AI 怎么写程序。
