### ISSUE TITLE
Podcast 目录可否收录王博士在龙行天下的节目？

### ISSUE THREAD

**Issue by xp01nt** [taizihuang/wmyblog#6]
最近王博每月一次在龙行天下的节目，已有十几期，可否转为音频一并收录至 Podcast 目录？
谢谢

**Comment by taizihuang** [comment]
好的，我这两天加上去。

不知道你是否有时间和精力帮忙一起制作“王孟源 x 龙行天下”音频的文字稿。我负责音频转文字和第一遍校对，你负责第二遍校对。

**Comment by xp01nt** [comment]
好的，我试试看。

**Comment by taizihuang** [comment]
我已经做好了，放在“最新访谈”网页中，请试用

**Comment by xp01nt** [comment]
> 我已经做好了，放在“最新访谈”网页中，请试用

感谢！

xml 标题部分有些残余的 html

**Comment by taizihuang** [comment]
我刚刚发现了一个小typo

你说的“残余的html”是什么，举个例子？

**Comment by xp01nt** [comment]
> 我刚刚发现了一个小typo
> 
> 你说的“残余的html”是什么，举个例子？

description 字段多了一个段落结束的 html， P 标签

**Comment by taizihuang** [comment]
了解，这个问题不大。以后可能会填时间戳进去，方便跳转章节

**Comment by jgong598** [comment]
@taizihuang 非常感谢你做的这个repo记录王孟源的文章！我一直也有想把他的所有八方论坛和龙行天下的节目，变成文字，方便检索。校对的工作我也感兴趣！
还有一个想法是把文字版的主持人的话和王孟源的话自动分出来。这个技术上应该能做到。
~~还有最后一个是可读性，一整大段比较难读，不知道有没有一个自动的方法可以分段，有时间我也想研究一下。~~
**Update**: 发现已经校对过的文章已经有把主持人的话和王孟源的话分出来了。分出来之后太大段话导致可读性下降的问题也不明显。

**Comment by taizihuang** [comment]
我五一期间把主持人和嘉宾的内容都分隔开来。目前陆陆续续有读者勘误，矫正格式，目前已经完成了25%。欢迎你有空也帮帮忙。

**Comment by taizihuang** [comment]
@JellyGong 现在的文字稿是用“飞书妙记”做一个初步的版本，效果非常好。你可以试试这个工具。
