### ISSUE TITLE
辛苦了

### ISSUE THREAD

**Issue by rewvbfdhgf** [taizihuang/wmyblog#8]
辛苦了，把王孟源的文章，访谈和文字版都总结出来了。厉害厉害！

**Comment by taizihuang** [comment]
客气。不过这并不是我一个人的贡献，我只是做了基础性工作。大部分的文字稿都是其他读者帮忙校对的。我知道的都放上了Credit，不过还有很多是匿名的。你如果有空，也可以帮忙调整格式，或者看看错别字哈。

**Comment by rewvbfdhgf** [comment]
好的，好的。
